export const ActionTypes = {
    FETCH_ALL_HELP_REQUEST: 'FETCH_ALL_HELP_REQUEST',
    FETCH_ALL_OFFER_REQUEST: 'FETCH_ALL_OFFER_REQUEST',
    GET_HELP_REQUEST_BY_ID: 'GET_HELP_REQUEST_BY_ID',
    GET_OFFER_REQUEST_BY_ID: 'GET_OFFER_REQUEST_BY_ID',
}