export const ActionTypes = {
    GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
    FETCH_ALL_HELP_REQUEST: 'FETCH_ALL_HELP_REQUEST',
    ADD_NEW_HELP_REQUEST: 'ADD_NEW_HELP_REQUEST',
    OFFER_NEW_HELP: 'OFFER_NEW_HELP'
}